# Generated by Django 5.1.1 on 2024-10-15 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("status", models.CharField(max_length=20)),
                ("order_date", models.CharField(blank=True, max_length=50, null=True)),
                ("select_time", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "Orders",
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                ("ticket_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=1000)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "TicketTypes",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Users",
            },
        ),
        migrations.CreateModel(
            name="DailyTicketQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "museum_ticket_type",
                    models.CharField(
                        choices=[
                            ("故宫", "故宫"),
                            ("珍宝馆", "珍宝馆"),
                            ("钟表馆", "钟表馆"),
                            ("展览", "展览"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                ("available_tickets", models.IntegerField(default=0)),
                (
                    "select_time",
                    models.CharField(
                        choices=[("上午", "上午"), ("下午", "下午")], max_length=10
                    ),
                ),
            ],
            options={
                "db_table": "DailyTicketQuota",
                "unique_together": {("date", "museum_ticket_type", "select_time")},
            },
        ),
        migrations.CreateModel(
            name="TicketSalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("sale_date", models.DateField()),
                ("select_time", models.CharField(max_length=10)),
                ("gugong_ticket_count", models.IntegerField(default=0)),
                ("treasure_island_ticket_count", models.IntegerField(default=0)),
                ("clock_museum_ticket_count", models.IntegerField(default=0)),
                ("exhibition_ticket_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "TicketSalesData",
                "unique_together": {("sale_date", "select_time")},
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "order_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name_1", models.CharField(blank=True, max_length=20, null=True)),
                ("id_card_1", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_type_1",
                    models.IntegerField(
                        choices=[
                            (0, "身份证"),
                            (1, "港澳居民往来内地通行证"),
                            (2, "外国人永久居留身份证"),
                            (3, "护照"),
                            (4, "台湾居民来往大陆通行证"),
                            (5, "港澳居民居住证"),
                        ],
                        default=0,
                    ),
                ),
                ("is_treasure_island_selected_1", models.BooleanField(default=False)),
                ("is_exhibition_selected_1", models.BooleanField(default=False)),
                ("is_clock_museum_selected_1", models.BooleanField(default=False)),
                ("name_2", models.CharField(blank=True, max_length=20, null=True)),
                ("id_card_2", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_type_2",
                    models.IntegerField(
                        choices=[
                            (0, "身份证"),
                            (1, "港澳居民往来内地通行证"),
                            (2, "外国人永久居留身份证"),
                            (3, "护照"),
                            (4, "台湾居民来往大陆通行证"),
                            (5, "港澳居民居住证"),
                        ],
                        default=0,
                    ),
                ),
                ("is_treasure_island_selected_2", models.BooleanField(default=False)),
                ("is_exhibition_selected_2", models.BooleanField(default=False)),
                ("is_clock_museum_selected_2", models.BooleanField(default=False)),
                ("name_3", models.CharField(blank=True, max_length=20, null=True)),
                ("id_card_3", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_type_3",
                    models.IntegerField(
                        choices=[
                            (0, "身份证"),
                            (1, "港澳居民往来内地通行证"),
                            (2, "外国人永久居留身份证"),
                            (3, "护照"),
                            (4, "台湾居民来往大陆通行证"),
                            (5, "港澳居民居住证"),
                        ],
                        default=0,
                    ),
                ),
                ("is_treasure_island_selected_3", models.BooleanField(default=False)),
                ("is_exhibition_selected_3", models.BooleanField(default=False)),
                ("is_clock_museum_selected_3", models.BooleanField(default=False)),
                ("name_4", models.CharField(blank=True, max_length=20, null=True)),
                ("id_card_4", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_type_4",
                    models.IntegerField(
                        choices=[
                            (0, "身份证"),
                            (1, "港澳居民往来内地通行证"),
                            (2, "外国人永久居留身份证"),
                            (3, "护照"),
                            (4, "台湾居民来往大陆通行证"),
                            (5, "港澳居民居住证"),
                        ],
                        default=0,
                    ),
                ),
                ("is_treasure_island_selected_4", models.BooleanField(default=False)),
                ("is_exhibition_selected_4", models.BooleanField(default=False)),
                ("is_clock_museum_selected_4", models.BooleanField(default=False)),
                ("name_5", models.CharField(blank=True, max_length=20, null=True)),
                ("id_card_5", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_type_5",
                    models.IntegerField(
                        choices=[
                            (0, "身份证"),
                            (1, "港澳居民往来内地通行证"),
                            (2, "外国人永久居留身份证"),
                            (3, "护照"),
                            (4, "台湾居民来往大陆通行证"),
                            (5, "港澳居民居住证"),
                        ],
                        default=0,
                    ),
                ),
                ("is_treasure_island_selected_5", models.BooleanField(default=False)),
                ("is_exhibition_selected_5", models.BooleanField(default=False)),
                ("is_clock_museum_selected_5", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gugong.order"
                    ),
                ),
                (
                    "audience_ticket_type_id_1",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_type_1",
                        to="gugong.tickettype",
                    ),
                ),
                (
                    "audience_ticket_type_id_2",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_type_2",
                        to="gugong.tickettype",
                    ),
                ),
                (
                    "audience_ticket_type_id_3",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_type_3",
                        to="gugong.tickettype",
                    ),
                ),
                (
                    "audience_ticket_type_id_4",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_type_4",
                        to="gugong.tickettype",
                    ),
                ),
                (
                    "audience_ticket_type_id_5",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_type_5",
                        to="gugong.tickettype",
                    ),
                ),
            ],
            options={
                "db_table": "OrderDetails",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="gugong.user",
            ),
        ),
        migrations.CreateModel(
            name="FrequentVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_1", models.CharField(blank=True, max_length=20, null=True)),
                ("id_card_1", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_type_1",
                    models.IntegerField(
                        choices=[
                            (0, "身份证"),
                            (1, "港澳居民往来内地通行证"),
                            (2, "外国人永久居留身份证"),
                            (3, "护照"),
                            (4, "台湾居民来往大陆通行证"),
                            (5, "港澳居民居住证"),
                        ],
                        default=0,
                    ),
                ),
                ("name_2", models.CharField(blank=True, max_length=20, null=True)),
                ("id_card_2", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_type_2",
                    models.IntegerField(
                        choices=[
                            (0, "身份证"),
                            (1, "港澳居民往来内地通行证"),
                            (2, "外国人永久居留身份证"),
                            (3, "护照"),
                            (4, "台湾居民来往大陆通行证"),
                            (5, "港澳居民居住证"),
                        ],
                        default=0,
                    ),
                ),
                ("name_3", models.CharField(blank=True, max_length=20, null=True)),
                ("id_card_3", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_type_3",
                    models.IntegerField(
                        choices=[
                            (0, "身份证"),
                            (1, "港澳居民往来内地通行证"),
                            (2, "外国人永久居留身份证"),
                            (3, "护照"),
                            (4, "台湾居民来往大陆通行证"),
                            (5, "港澳居民居住证"),
                        ],
                        default=0,
                    ),
                ),
                ("name_4", models.CharField(blank=True, max_length=20, null=True)),
                ("id_card_4", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_type_4",
                    models.IntegerField(
                        choices=[
                            (0, "身份证"),
                            (1, "港澳居民往来内地通行证"),
                            (2, "外国人永久居留身份证"),
                            (3, "护照"),
                            (4, "台湾居民来往大陆通行证"),
                            (5, "港澳居民居住证"),
                        ],
                        default=0,
                    ),
                ),
                ("name_5", models.CharField(blank=True, max_length=20, null=True)),
                ("id_card_5", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_type_5",
                    models.IntegerField(
                        choices=[
                            (0, "身份证"),
                            (1, "港澳居民往来内地通行证"),
                            (2, "外国人永久居留身份证"),
                            (3, "护照"),
                            (4, "台湾居民来往大陆通行证"),
                            (5, "港澳居民居住证"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequent_visitors",
                        to="gugong.user",
                    ),
                ),
            ],
            options={
                "db_table": "FrequentVisitors",
            },
        ),
        migrations.CreateModel(
            name="BookingRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "purchase_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gugong.order"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gugong.user"
                    ),
                ),
            ],
            options={
                "db_table": "BookingRecords",
            },
        ),
        migrations.CreateModel(
            name="YearTicketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=30)),
                ("date", models.DateField()),
                ("select_time", models.CharField(max_length=10)),
                ("ticket_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "YearTicketData",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "select_time"), name="unique_date_select_time"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="YearTicketQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_tickets", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_ticket_quota",
                        to="gugong.user",
                    ),
                ),
            ],
            options={
                "db_table": "YearTicketQuota",
            },
        ),
        migrations.CreateModel(
            name="DailyTicketSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=30)),
                ("date", models.DateField()),
                ("select_time", models.CharField(max_length=10)),
                ("ticket_count", models.IntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gugong.tickettype",
                    ),
                ),
            ],
            options={
                "db_table": "DailyTicketSale",
                "unique_together": {("ticket_type_id", "date", "select_time")},
            },
        ),
    ]
