# Generated by Django 5.1.1 on 2024-10-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gugong", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyticketsale",
            old_name="ticket_type_id",
            new_name="ticket_type",
        ),
    ]
